services:
  tutor-app:
    build: .
    container_name: tutor_app
    ports:
      - 8501:8501
    environment:
      - MONGO_URI=${MONGO_URI-mongodb://mongo:27017/comp1531_testing}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL-http://localhost:9200}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: es_container
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail http://localhost:9200/_cluster/health || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
