image: comp1531/automarking:latest

stages:
  - pipeline
  - deployment

pipeline:
  stage: pipeline
  script:
    - npm install
    - npm test
  only:
    - master
    - merge_requests
# deployment:
#   stage: deployment
#   needs: [pipeline]
#   resource_group: vercel-deploy
#   variables:
#     VERCEL_TOKEN: "CHANGE_THIS_HERE" # change this to your vercel token
#   script:
#     - npm install --global vercel@canary
#     - vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
#     - vercel deploy --prod --token=${VERCEL_TOKEN}
#   only: # change this if you want to deploy from other branches
#     - master
