openapi: 3.0.3
info:
  title: Checkins Server API
  description: |
    API for managing patient check-in admissions

    Please examine the example return values carefully when writing your tests.

    Moreover, next to the "Example Value" tab is the "Schema" tab, which will explain each attribute/property of an object in further details.

  version: 1.0.0
servers:
  - url: "{protocol}://{host}:{port}"
    variables:
      protocol:
        default: http
      host:
        default: '127.0.0.1'
      port:
        default: '49152'

tags:
  - name: Sample
    description: These are sample routes that we've already implemented for you!
  - name: Admissions
    description: Operation on hospital checkin admissions
  - name: Other
    description: Routes that don't fit in any of the categories above


paths:
  /:
    get:
      tags:
        - Sample
      summary: Displays a message
      description: This is the root route that has already been implemented for you. It returns a welcome message.
      responses:
        '200':
          description: "Returns a welcome message"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: "Welcome to Lab05 Checkins Server's root URL!"

  /echo/echo:
    get:
      tags:
        - Sample
      summary: Echo back a message
      description: |
        This is a sample echo route that has already been implemented for you.
        It returns a same message that was given in the query string, although an error is returned if you try to echo "echo".
      parameters:
        - name: message
          in: query
          required: true
          schema:
            type: string
            example: "helloworld!"

      responses:
        '200':
          description: "Echos the same mssage back"
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: "Helloworld!"
        '400':
          description: |
            If any of the following is true:
            - Attempting to echo the message "echo"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Cannot echo 'echo'!"
  /clear:
    delete:
      tags:
        - Other
      summary: "Clear all admissions. Difficulty: ⭐"
      description: Remove all checkin admissions from the data store.
      responses:
        '200':
          description: Admissions cleared successfully
          content:
            application/json:
              schema:
                type: object

  /admissions/checkin:
    post:
      tags:
        - Admissions
      summary: "Check in a patient. Difficulty: ⭐"
      description: Create a new admission in the data store, holding information about the patient's name, age and checkin time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - patientName
                - patientAge
              properties:
                patientName:
                  type: string
                  example: Bob
                patientAge:
                  type: integer
                  example: 23
      responses:
        '200':
          description: Check-in successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  admissionId:
                    type: integer
                    example: 1
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Age must be 0 or greater.

  /admissions/list:
    get:
      tags:
        - Admissions
      summary: "List admissions. Difficulty: ⭐"
      description: |
        List all admissions from patients who have checked in. If a `maxAge` is given in the
        query string of the request, only checkin admissions from patients whose age is equal to
        or lesser than the given `maxAge` is returned.
      parameters:
        - name: maxAge
          in: query
          required: true
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: List of admissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  admissions:
                    type: array
                    items:
                      type: object
                      properties:
                        admissionId:
                          type: integer
                          example: 1
                        patientName:
                          type: string
                          example: Bob
                        patientAge:
                          type: integer
                          example: 23
                        checkinTime:
                          type: integer
                          example: 1624455678
                          description: Integer unix timestamp (in seconds)
                        checkoutTime:
                          type: integer
                          nullable: true
                          example: null
                          description: |
                            This field has the value of null by default for admissions that were initially created,
                            and an integer UNIX timestamp (in seconds) when /admissions/:admissionid/checkout is called.
        '400':
          description: Invalid input (negative maxAge)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Max age must be 0 or greater

  /admissions/{admissionid}/checkout:
    post:
      tags:
        - Admissions
      summary: "Check out a patient. Difficulty: ⭐"
      description: Marks the checkout timestamp for an admission with a UNIX timestamp
      parameters:
        - name: admissionid
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Check-out successful
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid admission ID or already checked out
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "You have already checked out from the admission with id: 1"

  /admissions/{admissionid}:
    put:
      tags:
        - Admissions
      summary: "Update a patient's admission. Difficulty: ⭐"
      description: Update the name and age of a patient based on a particular admission.
      parameters:
        - name: admissionid
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - patientName
                - patientAge
              properties:
                patientName:
                  type: string
                  example: Edited
                patientAge:
                  type: integer
                  example: 999
      responses:
        '200':
          description: Update successful
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid input or admission ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No such admission with id: 1"
    delete:
      tags:
        - Admissions
      summary: "Delete a patient admission. Difficulty: ⭐"
      description: Given an admissionId, remove the corresponding admission.
      parameters:
        - name: admissionid
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Deletion successful
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid admission ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No such admission with id: 1"
